export const MANIFEST = [
  { id: 'text.case', group: 'Text', name: 'Change case', cost: 'linear', load: () => import('./text/case.js') },
  { id: 'text.normalizeNewlines', group: 'Text', name: 'Normalize newlines', cost: 'linear', load: () => import('./text/normalizeNewlines.js') },
  { id: 'text.normalizeUnicode', group: 'Text', name: 'Normalize Unicode', cost: 'linear', load: () => import('./text/normalizeUnicode.js') },
  { id: 'text.stripDiacritics', group: 'Text', name: 'Strip diacritics', cost: 'linear', load: () => import('./text/stripDiacritics.js') },
  { id: 'text.reverse', group: 'Text', name: 'Reverse', cost: 'linear', load: () => import('./text/reverse.js') },
  { id: 'text.pad', group: 'Text', name: 'Pad', cost: 'linear', load: () => import('./text/pad.js') },
  { id: 'text.truncate', group: 'Text', name: 'Truncate', cost: 'linear', load: () => import('./text/truncate.js') },
  { id: 'text.wrap', group: 'Text', name: 'Wrap', cost: 'linear', load: () => import('./text/wrap.js') },
  { id: 'text.slug', group: 'Text', name: 'Slugify', cost: 'linear', load: () => import('./text/slug.js') },

  { id: 'ws.trimLines', group: 'Whitespace', name: 'Trim lines', cost: 'linear', load: () => import('./ws/trimLines.js') },
  { id: 'ws.trimEdges', group: 'Whitespace', name: 'Trim document edges', cost: 'linear', load: () => import('./ws/trimEdges.js') },
  { id: 'ws.collapseSpaces', group: 'Whitespace', name: 'Collapse spaces', cost: 'linear', load: () => import('./ws/collapseSpaces.js') },
  { id: 'ws.tabsToSpaces', group: 'Whitespace', name: 'Tabs to spaces', cost: 'linear', load: () => import('./ws/tabsToSpaces.js') },
  { id: 'ws.spacesToTabs', group: 'Whitespace', name: 'Spaces to tabs', cost: 'linear', load: () => import('./ws/spacesToTabs.js') },
  { id: 'ws.stripTrailing', group: 'Whitespace', name: 'Strip trailing whitespace', cost: 'linear', load: () => import('./ws/stripTrailing.js') },
  { id: 'ws.removeBlank', group: 'Whitespace', name: 'Remove blank lines', cost: 'linear', load: () => import('./ws/removeBlank.js') },
  { id: 'ws.squeezeBlankLines', group: 'Whitespace', name: 'Squeeze blank lines', cost: 'linear', load: () => import('./ws/squeezeBlankLines.js') },
  { id: 'ws.indent', group: 'Whitespace', name: 'Indent lines', cost: 'linear', load: () => import('./ws/indent.js') },
  { id: 'ws.dedent', group: 'Whitespace', name: 'Dedent', cost: 'linear', load: () => import('./ws/dedent.js') },

  { id: 'lines.sort', group: 'Lines', name: 'Sort lines', cost: 'nlogn', load: () => import('./lines/sort.js') },
  { id: 'lines.dedupe', group: 'Lines', name: 'Dedupe lines', cost: 'linear', load: () => import('./lines/dedupe.js') },
  { id: 'lines.shuffle', group: 'Lines', name: 'Shuffle lines', cost: 'linear', load: () => import('./lines/shuffle.js') },
  { id: 'lines.number', group: 'Lines', name: 'Number lines', cost: 'linear', load: () => import('./lines/number.js') },
  { id: 'lines.filter', group: 'Lines', name: 'Filter lines', cost: 'linear', load: () => import('./lines/filter.js') },
  { id: 'lines.slice', group: 'Lines', name: 'Slice lines', cost: 'linear', load: () => import('./lines/slice.js') },
  { id: 'lines.prefixSuffix', group: 'Lines', name: 'Add prefix/suffix', cost: 'linear', load: () => import('./lines/prefixSuffix.js') },
  { id: 'lines.columnize', group: 'Lines', name: 'Columnize', cost: 'linear', load: () => import('./lines/columnize.js') },
  { id: 'lines.transpose', group: 'Lines', name: 'Transpose', cost: 'linear', load: () => import('./lines/transpose.js') },

  { id: 'find.replace', group: 'Find', name: 'Find & replace', cost: 'linear', load: () => import('./find/replace.js') },
  { id: 'find.replaceMany', group: 'Find', name: 'Replace many (translation table)', cost: 'linear', load: () => import('./find/replaceMany.js') },
  { id: 'find.highlight', group: 'Find', name: 'Highlight matches', cost: 'linear', load: () => import('./find/highlight.js') },
  { id: 'find.countMatches', group: 'Find', name: 'Count matches', cost: 'linear', load: () => import('./find/countMatches.js') },

  { id: 'split.byLines', group: 'Split', name: 'Split by lines', cost: 'linear', load: () => import('./split/byLines.js') },
  { id: 'split.bySize', group: 'Split', name: 'Split by size', cost: 'linear', load: () => import('./split/bySize.js') },
  { id: 'split.byRegex', group: 'Split', name: 'Split by pattern', cost: 'linear', load: () => import('./split/byRegex.js') },
  { id: 'split.byBlankLine', group: 'Split', name: 'Split by blank line', cost: 'linear', load: () => import('./split/byBlankLine.js') },
  { id: 'split.byHeading', group: 'Split', name: 'Split by heading', cost: 'linear', load: () => import('./split/byHeading.js') },
  { id: 'split.byDelimiterLine', group: 'Split', name: 'Split by delimiter line', cost: 'linear', load: () => import('./split/byDelimiterLine.js') },
  { id: 'split.byCount', group: 'Split', name: 'Split into N parts', cost: 'linear', load: () => import('./split/byCount.js') },
  { id: 'split.byToken', group: 'Split', name: 'Split by token (estimate)', cost: 'linear', load: () => import('./split/byToken.js') },

  { id: 'merge.concat', group: 'Merge', name: 'Concatenate', cost: 'linear', load: () => import('./merge/concat.js') },
  { id: 'merge.interleave', group: 'Merge', name: 'Interleave lines', cost: 'linear', load: () => import('./merge/interleave.js') },
  { id: 'merge.zipLines', group: 'Merge', name: 'Zip lines', cost: 'linear', load: () => import('./merge/zipLines.js') },
  { id: 'merge.joinLines', group: 'Merge', name: 'Join lines', cost: 'linear', load: () => import('./merge/joinLines.js') },
  { id: 'merge.reduceToTable', group: 'Merge', name: 'Reduce to table', cost: 'linear', load: () => import('./merge/reduceToTable.js') },
  { id: 'merge.wrapEach', group: 'Merge', name: 'Wrap each document', cost: 'linear', load: () => import('./merge/wrapEach.js') }
,
  { id: 'extract.byRegex', group: 'Extract', name: 'Extract by pattern', cost: 'linear', load: () => import('./extract/byRegex.js') },
  { id: 'extract.between', group: 'Extract', name: 'Extract between delimiters', cost: 'linear', load: () => import('./extract/between.js') },
  { id: 'extract.emails', group: 'Extract', name: 'Extract emails', cost: 'linear', load: () => import('./extract/emails.js') },
  { id: 'extract.urls', group: 'Extract', name: 'Extract URLs', cost: 'linear', load: () => import('./extract/urls.js') },
  { id: 'extract.ips', group: 'Extract', name: 'Extract IPv4 addresses', cost: 'linear', load: () => import('./extract/ips.js') },
  { id: 'extract.numbers', group: 'Extract', name: 'Extract numbers', cost: 'linear', load: () => import('./extract/numbers.js') },
  { id: 'extract.dates', group: 'Extract', name: 'Extract dates', cost: 'linear', load: () => import('./extract/dates.js') },
  { id: 'extract.quoted', group: 'Extract', name: 'Extract quoted strings', cost: 'linear', load: () => import('./extract/quoted.js') },
  { id: 'extract.hashtags', group: 'Extract', name: 'Extract hashtags', cost: 'linear', load: () => import('./extract/hashtags.js') },
  { id: 'extract.keyValue', group: 'Extract', name: 'Extract key/value pairs', cost: 'linear', load: () => import('./extract/keyValue.js') },
  { id: 'extract.columns', group: 'Extract', name: 'Extract columns', cost: 'linear', load: () => import('./extract/columns.js') },
  { id: 'extract.htmlText', group: 'Extract', name: 'Extract HTML text', cost: 'linear', load: () => import('./extract/htmlText.js') },
  { id: 'extract.htmlAttr', group: 'Extract', name: 'Extract HTML attribute', cost: 'linear', load: () => import('./extract/htmlAttr.js') },
  { id: 'extract.markdownHeadings', group: 'Extract', name: 'Extract Markdown headings', cost: 'linear', load: () => import('./extract/markdownHeadings.js') },
  { id: 'extract.codeBlocks', group: 'Extract', name: 'Extract code blocks', cost: 'linear', load: () => import('./extract/codeBlocks.js') },
  { id: 'extract.jsonPath', group: 'Extract', name: 'Extract by JSON path', cost: 'linear', load: () => import('./extract/jsonPath.js') },

  { id: 'gen.repeat', group: 'Gen', name: 'Repeat template', cost: 'linear', load: () => import('./gen/repeat.js') },
  { id: 'gen.sequence', group: 'Gen', name: 'Generate sequence', cost: 'linear', load: () => import('./gen/sequence.js') },
  { id: 'gen.fromList', group: 'Gen', name: 'Generate from list', cost: 'linear', load: () => import('./gen/fromList.js') },
  { id: 'gen.product', group: 'Gen', name: 'Cartesian product', cost: 'linear', load: () => import('./gen/product.js') },
  { id: 'gen.cycle', group: 'Gen', name: 'Cycle values onto lines', cost: 'linear', load: () => import('./gen/cycle.js') },
  { id: 'gen.lorem', group: 'Gen', name: 'Lorem ipsum', cost: 'linear', load: () => import('./gen/lorem.js') },

  { id: 'code.base64', group: 'Code', name: 'Base64', cost: 'linear', load: () => import('./code/base64.js') },
  { id: 'code.urlEncode', group: 'Code', name: 'URL encode/decode', cost: 'linear', load: () => import('./code/urlEncode.js') },
  { id: 'code.htmlEntities', group: 'Code', name: 'HTML entities', cost: 'linear', load: () => import('./code/htmlEntities.js') },
  { id: 'code.escapeJson', group: 'Code', name: 'Escape/unescape JSON string', cost: 'linear', load: () => import('./code/escapeJson.js') },
  { id: 'code.escapeCsv', group: 'Code', name: 'Escape/unescape CSV field', cost: 'linear', load: () => import('./code/escapeCsv.js') },
  { id: 'code.escapeRegex', group: 'Code', name: 'Escape/unescape regex', cost: 'linear', load: () => import('./code/escapeRegex.js') },
  { id: 'code.hex', group: 'Code', name: 'Hex', cost: 'linear', load: () => import('./code/hex.js') },
  { id: 'code.rot13', group: 'Code', name: 'ROT13', cost: 'linear', load: () => import('./code/rot13.js') },
  { id: 'code.quotedPrintable', group: 'Code', name: 'Quoted-printable', cost: 'linear', load: () => import('./code/quotedPrintable.js') },
  { id: 'code.hash', group: 'Code', name: 'Hash (SHA-256)', cost: 'linear', load: () => import('./code/hash.js') }
,
  { id: 'data.jsonFormat', group: 'Data', name: 'Format JSON', cost: 'linear', load: () => import('./data/jsonFormat.js') },
  { id: 'data.jsonMinify', group: 'Data', name: 'Minify JSON', cost: 'linear', load: () => import('./data/jsonMinify.js') },
  { id: 'data.jsonSortKeys', group: 'Data', name: 'Sort JSON keys', cost: 'linear', load: () => import('./data/jsonSortKeys.js') },
  { id: 'data.jsonFlatten', group: 'Data', name: 'Flatten JSON', cost: 'linear', load: () => import('./data/jsonFlatten.js') },
  { id: 'data.jsonToCsv', group: 'Data', name: 'JSON to CSV', cost: 'linear', load: () => import('./data/jsonToCsv.js') },
  { id: 'data.csvToJson', group: 'Data', name: 'CSV to JSON', cost: 'linear', load: () => import('./data/csvToJson.js') },
  { id: 'data.csvReshape', group: 'Data', name: 'Reshape CSV columns', cost: 'linear', load: () => import('./data/csvReshape.js') },
  { id: 'data.tsvSwap', group: 'Data', name: 'Swap CSV/TSV', cost: 'linear', load: () => import('./data/tsvSwap.js') },
  { id: 'data.toMarkdownTable', group: 'Data', name: 'To Markdown table', cost: 'linear', load: () => import('./data/toMarkdownTable.js') },

  { id: 'analyze.stats', group: 'Analyze', name: 'Document stats', cost: 'linear', load: () => import('./analyze/stats.js') },
  { id: 'analyze.frequency', group: 'Analyze', name: 'Word/char/n-gram frequency', cost: 'linear', load: () => import('./analyze/frequency.js') },
  { id: 'analyze.diff', group: 'Analyze', name: 'Diff documents', cost: 'linear', load: () => import('./analyze/diff.js') },
  { id: 'analyze.longestLines', group: 'Analyze', name: 'Longest lines', cost: 'nlogn', load: () => import('./analyze/longestLines.js') },
  { id: 'analyze.encodingReport', group: 'Analyze', name: 'Encoding report', cost: 'linear', load: () => import('./analyze/encodingReport.js') },
  { id: 'analyze.regexTester', group: 'Analyze', name: 'Regex tester', cost: 'linear', load: () => import('./analyze/regexTester.js') },

  { id: 'flow.select', group: 'Flow', name: 'Select documents', cost: 'linear', load: () => import('./flow/select.js') },
  { id: 'flow.rename', group: 'Flow', name: 'Rename documents', cost: 'linear', load: () => import('./flow/rename.js') },
  { id: 'flow.sortDocs', group: 'Flow', name: 'Sort documents', cost: 'nlogn', load: () => import('./flow/sortDocs.js') },
  { id: 'flow.group', group: 'Flow', name: 'Group into batches', cost: 'linear', load: () => import('./flow/group.js') },
  { id: 'flow.label', group: 'Flow', name: 'Label documents', cost: 'linear', load: () => import('./flow/label.js') },
  { id: 'flow.assert', group: 'Flow', name: 'Assert', cost: 'linear', load: () => import('./flow/assert.js') },
  { id: 'flow.script', group: 'Flow', name: 'Script', cost: 'linear', load: () => import('./flow/script.js') }
];
